# Autogenerated from a Treetop grammar. Edits may be lost.


module Twig
module Parsing

module Literal
  include Treetop::Runtime

  def root
    @root ||= :literal
  end

  include Integer

  include String

  def _nt_literal
    start_index = index
    if node_cache[:literal].has_key?(index)
      cached = node_cache[:literal][index]
      if cached
        node_cache[:literal][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0 = index
    r1 = _nt_string
    if r1
      r1 = SyntaxNode.new(input, (index-1)...index) if r1 == true
      r0 = r1
    else
      r2 = _nt_integer
      if r2
        r2 = SyntaxNode.new(input, (index-1)...index) if r2 == true
        r0 = r2
      else
        @index = i0
        r0 = nil
      end
    end

    node_cache[:literal][start_index] = r0

    r0
  end

end

class LiteralParser < Treetop::Runtime::CompiledParser
  include Literal
end


end
end