# Autogenerated from a Treetop grammar. Edits may be lost.


module Twig
module Parsing

module Statement
  include Treetop::Runtime

  def root
    @root ||= :statement
  end

  def _nt_statement
    start_index = index
    if node_cache[:statement].has_key?(index)
      cached = node_cache[:statement][index]
      if cached
        node_cache[:statement][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    if (match_len = has_terminal?("dummy", false, index))
      r0 = instantiate_node(SyntaxNode,input, index...(index + match_len))
      @index += match_len
    else
      terminal_parse_failure('"dummy"')
      r0 = nil
    end

    node_cache[:statement][start_index] = r0

    r0
  end

end

class StatementParser < Treetop::Runtime::CompiledParser
  include Statement
end


end
end